adminapp/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from .views import*


urlpatterns=[
    path('dash',views.index,name="dash"),
    path('register/', views.register, name='register'),
    path('custmng/', views.custmng, name='custmng'),
    path('logout',logout,name="logout"),
    path('delcust/<id>',views.delcust,name="delcust"),
    path('provider',views.provider,name="provider"),
    path('delprovider/<id>',views.delprovider,name="delprovider"),
    path('admin_inquiries', views.inquiry_admin_view, name="inquiries"),
    path('vehicle', views.vehicle, name = "vehicle"),
    path('delvehicle/<id>',views.delvehicle,name="delvehicle"),
    path('bookings_details', views.booking_details, name = 'bookings_details'),
    path('logout',views.logout,name="logout"),
   
    
    
]

clientapp/urls.py
from django.urls import path
from .import views

urlpatterns=[
   path('clientapp/',views.clientdash,name="clientdash"),
   path('clientlogout/',views.clientlogout,name="clientlogout"),
]

ride_rover/urls.py
from django.contrib import admin
from django.urls import path,include
from user import views
from django.conf.urls.static import static
from django.conf import settings 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('user.userurls')),
    path('adminapp/',include(('adminapp.urls','adminapp'),namespace="adminapp")),
    path('clientapp/',include(('clientapp.urls','clientapp'),namespace="clientapp")),
    
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

clientapp/models.py
from django.db import models

# Create your models here.

clientapp/views.py
from django.shortcuts import render,redirect
from user.models import*
from django.views.decorators.cache import cache_control
from django.core.files.storage import FileSystemStorage
# Create your views here.
def clientdash(request):
    return render(request,'clienthome.html')

def clientlogout(request):
    try:
        if request.session['student']!=None:
            del request.session['student']
            return redirect('signin')
    except:
        return redirect('signin')

clientapp/templates/clienthome.html
{% extends "clientparent.html" %}
{% block body %}
    <div class="row">
        <div class="col-sm-12">
            <h1 style="text-align:center;">Customer</h1>   
              
        </div>
    </div>
{% endblock body %}

clientapp/templates/clientparent.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ride_Rover Client Panel</title>
    <link rel="stylesheet" href="{% static 'assets/vendors/mdi/css/materialdesignicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/css/vendor.bundle.base.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/jvectormap/jquery-jvectormap.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/flag-icon-css/css/flag-icon.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/owl-carousel-2/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/owl-carousel-2/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'assets/images/favicon.png' %}" />
    <style>
      input, textarea {
        color: white !important;
      }
      ::placeholder {
        color: white !important;
      }
    </style>
</head>
<body>
    <div class="container-scroller">
      <!-- Sidebar -->
      <nav class="sidebar sidebar-offcanvas" id="sidebar">
          <div class="sidebar-brand-wrapper d-none d-lg-flex align-items-center justify-content-center fixed-top">
            <span>ride_rover Customer</span>
          </div>
          <ul class="nav">
            <li class="nav-item profile">
              <div class="profile-desc">
                <div class="profile-pic">
                  <div class="count-indicator">
                    <img class="img-xs rounded-circle" src="{% static 'assets/images/faces/face15.jpg' %}" alt="">
                    <span class="count bg-success"></span>
                  </div>
                  <div class="profile-name">
                    <h5 class="mb-0 font-weight-normal">Customer</h5>                    
                  </div>
                </div>
                <a href="#" id="profile-dropdown" data-bs-toggle="dropdown"><i class="mdi mdi-dots-vertical"></i></a>
                <div class="dropdown-menu dropdown-menu-right sidebar-dropdown preview-list">
                  <a href="#" class="dropdown-item preview-item">
                    <div class="preview-thumbnail">
                      <div class="preview-icon bg-dark rounded-circle">
                        <i class="mdi mdi-settings text-primary"></i>
                      </div>
                    </div>
                    <div class="preview-item-content">
                      <p class="preview-subject ellipsis mb-1 text-small">Profile Management</p>
                    </div>
                  </a>
                  <div class="dropdown-divider"></div>
                  <a href="#" class="dropdown-item preview-item">
                    <div class="preview-thumbnail">
                      <div class="preview-icon bg-dark rounded-circle">
                        <i class="mdi mdi-onepassword text-info"></i>
                      </div>
                    </div>
                    <div class="preview-item-content">
                      <p class="preview-subject ellipsis mb-1 text-small">Change Password</p>
                    </div>
                  </a>
                  <div class="dropdown-divider"></div>
                  <a href="{%url 'clientapp:clientlogout'%}" class="dropdown-item preview-item">
                    <div class="preview-thumbnail">
                      <div class="preview-icon bg-dark rounded-circle">
                        <i class="mdi mdi-calendar-today text-success"></i>
                      </div>
                    </div>
                    <div class="preview-item-content">
                      <p class="preview-subject ellipsis mb-1 text-small">Logout</p>
                    </div>
                  </a>
                </div>
              </div>
            </li>            

            <!-- Navigation Links -->
            <li class="nav-item menu-items">
              <a class="nav-link" href="#">
                <span class="menu-icon">
                  <i class="mdi mdi-speedometer"></i>
                </span>
                <span class="menu-title">Dashboard</span>
              </a>
            </li>
             
           
            <li class="nav-item menu-items">
              <a class="nav-link" href="#">
                <span class="menu-icon">
                  <i class="mdi mdi-clipboard-text"></i>
                </span>
                <span class="menu-title">Booking History</span>
              </a>
            </li>
           
           
          </ul>
        </nav>
        
        <!-- Main Content -->
        <div class="container-fluid page-body-wrapper">
          <nav class="navbar p-0 fixed-top d-flex flex-row">
            <div class="navbar-brand-wrapper d-flex d-lg-none align-items-center justify-content-center">
              <a class="navbar-brand brand-logo-mini" href="#"><img src="{% static 'assets/images/logo-mini.svg' %}" alt="logo" /></a>
            </div>
            <div class="navbar-menu-wrapper flex-grow d-flex align-items-stretch">
              <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
                <span class="mdi mdi-menu"></span>
              </button>
              <ul class="navbar-nav navbar-nav-right">
                <li class="nav-item dropdown">
                  <a class="nav-link" id="profileDropdown" href="#" data-bs-toggle="dropdown">
                    <div class="navbar-profile">
                      <img class="img-xs rounded-circle" src="{% static 'assets/images/faces/face15.jpg' %}" alt="">
                      <p class="mb-0 d-none d-sm-block navbar-profile-name">{{ cust.name }}</p>
                      <i class="mdi mdi-menu-down d-none d-sm-block"></i>
                    </div>
                  </a>
                  <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list">
                    <a class="dropdown-item preview-item">
                      <div class="preview-thumbnail">
                        <div class="preview-icon bg-dark rounded-circle">
                          <i class="mdi mdi-settings text-success"></i>
                        </div>
                      </div>
                      <div class="preview-item-content">
                        <p class="preview-subject mb-1">Settings</p>
                      </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="{%url 'clientapp:clientlogout'%}" class="dropdown-item preview-item">
                      <div class="preview-thumbnail">
                        <div class="preview-icon bg-dark rounded-circle">
                          <i class="mdi mdi-logout text-danger"></i>
                        </div>
                      </div>
                      <div class="preview-item-content">
                        <p class="preview-subject mb-1">Log out</p>
                      </div>
                    </a>
                  </div>
                </li>
              </ul>
              <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
                <span class="mdi mdi-format-line-spacing"></span>
              </button>
            </div>
          </nav>
          
          <div class="main-panel">
            <div class="content-wrapper">
              {% block body %}              
              {% endblock body %}
            </div>
          
            <footer class="footer">
              <div class="d-sm-flex justify-content-center justify-content-sm-between">
                <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © Ride_Rover 2024</span>
                <span class="text-muted d-block text-center">Terms and Privacy | Contact Us</span>
              </div>
            </footer>
          </div>
        </div>
      </div>

      <!-- Scripts -->
      <script src="{% static 'assets/vendors/js/vendor.bundle.base.js' %}"></script>
      <script src="{% static 'assets/vendors/chart.js/Chart.min.js' %}"></script>
      <script src="{% static 'assets/js/dashboard.js'%}"></script>
    </body>
</html>