adminapp/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from .views import*


urlpatterns=[
    path('dash',views.index,name="dash"),
    path('register/', views.register, name='register'),
    path('custmng/', views.custmng, name='custmng'),
    path('logout',logout,name="logout"),
    path('delcust/<id>',views.delcust,name="delcust"),
    path('provider',views.provider,name="provider"),
    path('delprovider/<id>',views.delprovider,name="delprovider"),
    path('admin_inquiries', views.inquiry_admin_view, name="inquiries"),
    path('vehicle', views.vehicle, name = "vehicle"),
    path('delvehicle/<id>',views.delvehicle,name="delvehicle"),
    path('bookings_details', views.booking_details, name = 'bookings_details'),
    path('logout',views.logout,name="logout"),
   
    
    
]

ride_rover/urls.py
from django.contrib import admin
from django.urls import path,include
from user import views
from django.conf.urls.static import static
from django.conf import settings 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('user.userurls')),
    path('adminapp/',include(('adminapp.urls','adminapp'),namespace="adminapp")),
    path('clientapp/',include(('clientapp.urls','clientapp'),namespace="clientapp")),
    
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django import forms
from user.models import *

class RegistrationForm(forms.ModelForm):
    class Meta:
        model = Registration
        fields = ['fullname', 'emailid', 'mob_number', 'licensenumber', 'licensepic', 'userpic', 'signpic']
        widgets = {
            'licensepic': forms.ClearableFileInput(attrs={'accept': 'image/*'}),
            'userpic': forms.ClearableFileInput(attrs={'accept': 'image/*'}),
            'signpic': forms.ClearableFileInput(attrs={'accept': 'image/*'}),
        }

# class BookingForm(forms.ModelForm):
#     class Meta:
#         model = Booking
#         fields = ['booking_type', 'pickup_date', 'pickup_time', 'dropoff_date', 'dropoff_time']
#         widgets = {
#             'pickup_date': forms.DateInput(attrs={'type': 'date'}),
#             'dropoff_date': forms.DateInput(attrs={'type': 'date'}),
#             'pickup_time': forms.TimeInput(attrs={'type': 'time'}),
#             'dropoff_time': forms.TimeInput(attrs={'type': 'time'}),
#         }

class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ['booking_type', 'pickup_date', 'pickup_time', 'dropoff_date', 'dropoff_time']
        widgets = {
            'pickup_date': forms.DateInput(attrs={'type': 'date'}),
            'pickup_time': forms.TimeInput(attrs={'type': 'time'}),
            'dropoff_date': forms.DateInput(attrs={'type': 'date'}),
            'dropoff_time': forms.TimeInput(attrs={'type': 'time'}),
        }

adminapp/views.py
from django.shortcuts import render,redirect,get_object_or_404
import datetime
from user.models import *
from .forms import *
from django.http import JsonResponse
from datetime import datetime

def index(request):
    if 'username' in request.session:
        provider.count = Provider.objects.all().count
        register.count = Registration.objects.all().count
        
        return render(request,'adminhome.html',locals())
    else:
        return redirect('login')

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST, request.FILES)
        if form.is_valid():
           
            customer = Registration(
                fullname=form.cleaned_data['fullname'],
                email=form.cleaned_data['emailid'],
                mob_number=form.cleaned_data['mob_number'],
                licensenumber=form.cleaned_data['licensenumber'],
                licensepic=form.cleaned_data['licensepic'],
                userpic=form.cleaned_data['userpic'],
                signpic=form.cleaned_data['signpic']
            )
            customer.save()
            return redirect('success')  
    else:
        form = RegistrationForm()

    return render(request, 'registration.html', {'form': form})

def custmng(request):
    users = Registration.objects.all()  
    context = {
        'users': users,
    }
    return render(request, 'custmng.html', {'users': users})

def logout(request):
    request.session.flush()

def delcust(request,id):
    try:
        if request.session['username']!=None:
            Registration.objects.get(id=id).delete()
            return redirect('adminapp:custmng')
    except:
        return redirect('ride')

def provider(request):
    #try:
        if request.session['username']!=None:
            p=Provider.objects.all()
            if request.method=="POST":
                name=request.POST['name']
                email=request.POST['email']
                phone=request.POST['phone']
                address=request.POST['address']
                vehicle_name=request.POST['vehicle_name']
                vehicle_number=request.POST['vehicle_number']
                year=request.POST['year']
                date_joined=request.POST['date_joined']
                is_active=request.POST['is_active']
                provider_img=request.POST['provider_image']
                vehicle_img=request.POST['vehicle_image']
                p=Provider(name=name,email=email,phone=phone, address=address, vehicle_name=vehicle_name,vehicle_number=vehicle_number,year=year, date_joined = date_joined,is_active = is_active, provider_img = provider_img, vehicle_img=vehicle_img )
                p.save()
                return redirect('adminapp:provider')
            return render(request,'provider.html',locals())
    #except:
            return(redirect('ride'))
        
def delprovider(request,id):
     try:
          if request.session['username']!=None:
               Provider.objects.get(id=id).delete()
               return redirect('adminapp:provider')
     except:
          return redirect('ride')
     
def inquiry_admin_view(request):
    inquiries = Inquiry.objects.all().order_by('-submitted_at')  
    return render(request, 'admin_inquiries.html', {'inquiries': inquiries})

def vehicle(request):
    vehicle = Vehicle.objects.all()
    return render(request, 'vehicle.html', {'vehicle':vehicle} )

def delvehicle(request,id):
     try:
          if request.session['username']!=None:
               Vehicle.objects.get(id=id).delete()
               return redirect('adminapp:Vehicle')
     except:
          return redirect('ride')

def booking_details(request):
    bookings = Booking.objects.all() 
    return render(request, "bookings_details.html", {"bookings": bookings})

def logout(request):
    try:
        if request.session['username']!=None:
            del request.session['username']
            return redirect('signin')
    except:
        return redirect('signin')

adminapp/templates/admin_inquiries.html
{% extends "adminparent.html" %}

{% block body %}
<div class="container mt-5">
    <h2 class="text-center text-primary">User Inquiries</h2>
    <table class="table table-bordered  mt-4">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Mobile</th>
                <th>Email</th>
                <th>Subject</th>
                <th>Message</th>
                <th>Submitted At</th>
            </tr>
        </thead>
        <tbody>
            {% for inquiry in inquiries %}
            <tr>
                <td>{{ inquiry.id }}</td>
                <td>{{ inquiry.name }}</td>
                <td>{{ inquiry.mobile }}</td>
                <td>{{ inquiry.email }}</td>
                <td>{{ inquiry.subject }}</td>
                <td>{{ inquiry.message }}</td>
                <td>{{ inquiry.submitted_at|date:"Y-m-d H:i" }}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="7" class="text-center">No inquiries found.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

adminapp/templates/adminhome.html
{% extends "adminparent.html" %}
{% block body %}
    <div class="row">
        <div class="col-sm-12">
            <h1 style="text-align:center;">Admin Home</h1>   
            <div class="row my-4">
            <div class="col-sm-4">
                <div class="card shadow p-3">
                    <h4><i class="fa-solid fa-user-graduate fs-1 ms-3 text-warning"></i><span class="ms-5">Providers</span></h4>
                    <h3 class="text-center pt-3 text-warning">{{provider_count}}</h3>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="card shadow p-3">
                    <h4><i class="fa-solid fa-chalkboard-user fs-1 ms-3 text-primary"></i><span class="ms-5">Users </span></h4>
                    <h3 class="text-center pt-3 text-primary">{{register_count}}</h3>
                </div>
            </div>
            
            <div class="col-sm-4">
                <div class="card shadow p-3">
                    <h4><i class="fa-solid fa-users-rectangle fs-1 ms-3 text-success"></i><span class="ms-5"></span></h4>
                    <h3 class="text-center pt-3 text-success"></h3>
                </div>
            </div>
            <div class="col-sm-4 my-4">
                <div class="card shadow p-3">
                    <h4><i class="fa-solid fa-book fs-1 ms-3 text-danger"></i><span class="ms-5"></span></h4>
                    <h3 class="text-center pt-3 text-danger"></h3>
                </div>
            </div>
            </div>
        </div>
    </div>
{% endblock body %}

adminapp/templates/adminparent.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ride_Rover Admin Panel</title>
    <link rel="stylesheet" href="{% static 'assets/vendors/mdi/css/materialdesignicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/css/vendor.bundle.base.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/jvectormap/jquery-jvectormap.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/flag-icon-css/css/flag-icon.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/owl-carousel-2/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/owl-carousel-2/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'assets/images/favicon.png' %}" />
    <style>
      input, textarea {
        color: white !important;
      }
      ::placeholder {
        color: white !important;
      }
    </style>
</head>
<body>
    <div class="container-scroller">
      <!-- Sidebar -->
      <nav class="sidebar sidebar-offcanvas" id="sidebar">
          <div class="sidebar-brand-wrapper d-none d-lg-flex align-items-center justify-content-center fixed-top">
            <span>ride_rover admin</span>
          </div>
          <ul class="nav">
            <li class="nav-item profile">
              <div class="profile-desc">
                <div class="profile-pic">
                  <div class="count-indicator">
                    <img class="img-xs rounded-circle" src="{% static 'assets/images/faces/face15.jpg' %}" alt="">
                    <span class="count bg-success"></span>
                  </div>
                  <div class="profile-name">
                    <h5 class="mb-0 font-weight-normal">Admin</h5>                    
                  </div>
                </div>
                <a href="#" id="profile-dropdown" data-bs-toggle="dropdown"><i class="mdi mdi-dots-vertical"></i></a>
                <div class="dropdown-menu dropdown-menu-right sidebar-dropdown preview-list">
                  <a href="#" class="dropdown-item preview-item">
                    <div class="preview-thumbnail">
                      <div class="preview-icon bg-dark rounded-circle">
                        <i class="mdi mdi-settings text-primary"></i>
                      </div>
                    </div>
                    <div class="preview-item-content">
                      <p class="preview-subject ellipsis mb-1 text-small">Profile Management</p>
                    </div>
                  </a>
                  <div class="dropdown-divider"></div>
                  <a href="#" class="dropdown-item preview-item">
                    <div class="preview-thumbnail">
                      <div class="preview-icon bg-dark rounded-circle">
                        <i class="mdi mdi-onepassword text-info"></i>
                      </div>
                    </div>
                    <div class="preview-item-content">
                      <p class="preview-subject ellipsis mb-1 text-small">Change Password</p>
                    </div>
                  </a>
                  <div class="dropdown-divider"></div>
                  <a href="{%url 'adminapp:logout'%}" class="dropdown-item preview-item">
                    <div class="preview-thumbnail">
                      <div class="preview-icon bg-dark rounded-circle">
                        <i class="mdi mdi-calendar-today text-success"></i>
                      </div>
                    </div>
                    <div class="preview-item-content">
                      <p class="preview-subject ellipsis mb-1 text-small">Logout</p>
                    </div>
                  </a>
                </div>
              </div>
            </li>            

            <!-- Navigation Links -->
            <li class="nav-item menu-items">
              <a class="nav-link" href="{% url 'adminapp:dash' %}">
                <span class="menu-icon">
                  <i class="mdi mdi-speedometer"></i>
                </span>
                <span class="menu-title">Dashboard</span>
              </a>
            </li>
            <li class="nav-item menu-items">
              <a class="nav-link" href="{% url 'adminapp:vehicle' %}">
                <span class="menu-icon">
                  <i class="mdi mdi-car"></i>
                </span>
                <span class="menu-title">Manage Vehicles</span>
              </a>
            </li>    
            <li class="nav-item menu-items">
              
              <a class="nav-link" href="{% url 'adminapp:custmng' %}">
                <span class="menu-icon">
                  <i class="mdi mdi-account-multiple"></i>
                </span>
                <span class="menu-title">Customer Management</span>
              </a>
            </li>
           
          <li class="nav-item menu-items">
          <a class="nav-link" href="{% url 'adminapp:bookings_details' %}">
            <span class="menu-icon">
                <i class="mdi mdi-clipboard-text"></i>
            </span>
            <span class="menu-title"> Customer Booking  </span>
        </a>
          </li>
          
              
          
          
            <li class="nav-item menu-items">
              <a class="nav-link" href="{% url 'adminapp:inquiries' %}">
                <span class="menu-icon">
                  <i class="mdi mdi-comment-account"></i>
                </span>
                <span class="menu-title">Customer Enquiry</span>
              </a>
            </li>
            
            <li class="nav-item menu-items">
              <a class="nav-link" href="{% url 'adminapp:provider' %}">
                <span class="menu-icon">
                  <i class="mdi mdi-domain"></i>
                </span>
                <span class="menu-title">Provider Management</span>
              </a>
            </li>
          </ul>
        </nav>
        
        <!-- Main Content -->
        <div class="container-fluid page-body-wrapper">
          <nav class="navbar p-0 fixed-top d-flex flex-row">
            <div class="navbar-brand-wrapper d-flex d-lg-none align-items-center justify-content-center">
              <a class="navbar-brand brand-logo-mini" href="#"><img src="{% static 'assets/images/logo-mini.svg' %}" alt="logo" /></a>
            </div>
            <div class="navbar-menu-wrapper flex-grow d-flex align-items-stretch">
              <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
                <span class="mdi mdi-menu"></span>
              </button>
              <ul class="navbar-nav navbar-nav-right">
                <li class="nav-item dropdown">
                  <a class="nav-link" id="profileDropdown" href="#" data-bs-toggle="dropdown">
                    <div class="navbar-profile">
                      <img class="img-xs rounded-circle" src="{% static 'assets/images/faces/face15.jpg' %}" alt="">
                      <p class="mb-0 d-none d-sm-block navbar-profile-name">{{ cust.name }}</p>
                      <i class="mdi mdi-menu-down d-none d-sm-block"></i>
                    </div>
                  </a>
                  <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list">
                    <a class="dropdown-item preview-item">
                      <div class="preview-thumbnail">
                        <div class="preview-icon bg-dark rounded-circle">
                          <i class="mdi mdi-settings text-success"></i>
                        </div>
                      </div>
                      <div class="preview-item-content">
                        <p class="preview-subject mb-1">Settings</p>
                      </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="{%url 'adminapp:logout'%}" class="dropdown-item preview-item">
                      <div class="preview-thumbnail">
                        <div class="preview-icon bg-dark rounded-circle">
                          <i class="mdi mdi-logout text-danger"></i>
                        </div>
                      </div>
                      <div class="preview-item-content">
                        <p class="preview-subject mb-1">Log out</p>
                      </div>
                    </a>
                  </div>
                </li>
              </ul>
              <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
                <span class="mdi mdi-format-line-spacing"></span>
              </button>
            </div>
          </nav>
          
          <div class="main-panel">
            <div class="content-wrapper">
              {% block body %}              
              {% endblock body %}
            </div>
          
            <footer class="footer">
              <div class="d-sm-flex justify-content-center justify-content-sm-between">
                <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © Ride_Rover 2024</span>
                <span class="text-muted d-block text-center">Terms and Privacy | Contact Us</span>
              </div>
            </footer>
          </div>
        </div>
      </div>

      <!-- Scripts -->
      <script src="{% static 'assets/vendors/js/vendor.bundle.base.js' %}"></script>
      <script src="{% static 'assets/vendors/chart.js/Chart.min.js' %}"></script>
      <script src="{% static 'assets/js/dashboard.js'%}"></script>
    </body>
</html>

adminapp/templates/bookings_details.html
{% extends "adminparent.html" %}

{% block body %}
<div class="container mt-5">
    <h1 class="mb-4 text-center text-danger">Booking Details</h1>
    <table class="table table-bordered table-responsive text-white">
        <thead>
           
            <tr>
               
                <th>ID</th>
                <th>User</th>
                <th>Vehicle</th>
                <th>Booking Type</th>
                <th>Pickup Date</th>
                <th>Dropoff Date</th>
                <th>Total Amount</th>
                <th>Payment</th>
            </tr>
        
        </thead>
        <tbody>
            {% for booking in bookings %}
            <tr>
                <td>{{ booking.booking_id }}</td>
                <td>{{ booking.user.username }}</td>
                <td>Bajaj Pulsar</td>
                <td>{{ booking.booking_type }}</td>
                <td>{{ booking.pickup_date }}</td>
                <td>{{ booking.dropoff_date }}</td>
                <td>₹{{ booking.total_amount }}</td>
                <td><select id="payment-method" name="payment_method" class="form-select" required>
                    <option value="cash">Cash</option>
                    <option value="online">Online</option>
                </select></td>
                <script>
                    
                    const paymentMethod = document.getElementById('payment-method');
                
                    
                    paymentMethod.addEventListener('change', function() {
                        
                        paymentMethod.style.backgroundColor = 'green';
                    });
                </script>
            </tr>
            {% empty %}
            <tr>
                <td colspan="7" class="text-center">No bookings found</td>
            </tr>
            {% endfor %}
            
        </tbody>
    </table>
    
</div>
{% endblock %}

adminapp/templates/custmng.html
{% extends 'adminparent.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin- Customer Management </title>
</head>
<body>
    

{% block body %}
<h1 class="text-center text-success"><u>Customer Management</u></h1>
    <h2 class="text-center">Registered Users</h2>
    <table border="1" class=" table-bordered table-responsive mx-auto ">
        <thead class="text-center">
            <tr>
                <th>ID</th>
                <th>Full Name</th>
                <th>Email</th>
                <th>Password</th>
                <th>Mobile Number</th>
                <th>License Number</th>
                <th>License Picture</th>
                <th>Signature Picture</th>
                <th colspan="2">Action</th>
                
            </tr>
        </thead>
        <tbody class="text-center">
            {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.fullname }}</td>
                <td>{{ user.emailid }}</td>
                <td>{{ user.password }}</td>
                <td>{{ user.mob_number }}</td>
                <td>{{ user.licensenumber }}</td>
                <td><img src="{{ user.licensepic.url }}" alt="License" width="100"></td>
                <td><img src="{{ user.signpic.url }}" alt="Signature" width="100"></td>
                
                <td><a href="{% url 'adminapp:delcust' id=user.id %}" class="btn btn-danger">Delete</a></td>
               <td><button class="btn btn-primary" onclick="verifyUser(this)">Verify</button></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <script type="text/javascript">
        
        function verifyUser(button) {
            alert("User Verified");
            button.classList.remove('btn-primary');
            button.classList.add('btn-success');
            button.innerText = 'Verified';  
        }
    </script>
   
    {% endblock %}
</body>
</html>

adminapp/templates/provider.html
{% extends "adminparent.html" %}
{% block body %}
<div class="container my-5">
    
    <div class="row">
        <div class="col-12">
            <h1 class="text-center text-warning mb-4 ">Manage Providers</h1>
        </div>
    </div>

    <!-- Add Provider Form -->
    <div class="row justify-content-center">
        <div class="col-lg-8 col-md-10">
            <form action="" method="post" enctype="multipart/form-data" class="card bg-dark text-light p-4 shadow rounded">
                {% csrf_token %}
                <u><h4 class="card-title text-center mb-4">Add New Provider</h4></u>
                <div class="form-group mb-3">
                    <label for="name">Provider Name</label>
                    <input type="text" name="name" id="name" class="form-control" placeholder="Enter provider's name" required>
                </div>
                <div class="form-group mb-3">
                    <label for="email">Email ID</label>
                    <input type="email" name="email" id="email" class="form-control" placeholder="Enter provider's email" required>
                </div>
                <div class="form-group mb-3">
                    <label for="phone">Contact Number</label>
                    <input type="text" name="phone" id="phone" class="form-control" placeholder="Enter contact number" required>
                </div>
                <div class="form-group mb-3">
                    <label for="address">Address</label>
                    <textarea name="address" id="address" class="form-control" rows="3" placeholder="Enter provider's address" required></textarea>
                </div>
                <div class="form-group mb-3">
                    <label for="vehicle_name">Vehicle Name</label>
                    <input type="text" name="vehicle_name" id="vehicle_name" class="form-control" placeholder="Enter vehicle name" required>
                </div>
                <div class="form-group mb-3">
                    <label for="vehicle_number">Vehicle Number</label>
                    <input type="text" name="vehicle_number" id="vehicle_number" class="form-control" placeholder="Enter vehicle number" required>
                </div>
                <div class="form-group mb-3">
                    <label for="year">Year of Purchasing</label>
                    <input type="date" name="year" id="year" class="form-control" required>
                </div>
                <div class="form-group mb-3">
                    <label for="date_joined">Date Joined</label>
                    <input type="date" name="date_joined" id="date_joined" class="form-control" required>
                </div>
                <div class="form-group mb-3 ">
                    <label for="is_active">Active</label>
                    <select name="is_active" id="is_active" class="form-control text-light" >
                        <option value="Yes">Yes</option>
                        <option value="No">No</option>
                    </select>
                </div>
                <div class="form-group mb-3">
                    <label for="provider_img">Provider Image</label>
                    <input type="file" name="provider_img" id="provider_img" class="form-control">
                </div>
                <div class="form-group mb-3">
                    <label for="vehicle_img">Vehicle Image</label>
                    <input type="file" name="vehicle_img" id="vehicle_img" class="form-control">
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-success px-5">Add Provider</button>
                </div>
            </form>
        </div>
    </div>

   
    <div class="row mt-5">
        <div class="col-12 table-responsive">
            <h4 class="text-center text-light mb-4">Provider Details</h4>
            <table class="table table-striped table-bordered text-center text-light  ">
                <thead class="thead-dark">
                    <tr>
                        <th>Provider ID</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Contact</th>
                        <th>Address</th>
                        <th>Vehicle Name</th>
                        <th>Vehicle Number</th>
                        <th>Year of Purchase</th>
                        <th>Join Date</th>
                        <th>Active</th>
                        <th>Provider Image</th>
                        <th>Vehicle Image</th>
                        <th>Action</th>
                        

                    </tr>
                </thead>
                <tbody>
                
                    {% for pr in p %}
                    <tr>
                        <td>{{ pr.id }}</td>
                        <td>{{ pr.name }}</td>
                        <td>{{ pr.email }}</td>
                        <td>{{ pr.phone }}</td>
                        <td>{{ pr.address }}</td>
                        <td>{{ pr.vehicle_name }}</td>
                        <td>{{ pr.vehicle_number }}</td>
                        <td>{{ pr.year }}</td>
                        <td>{{ pr.date_joined }}</td>
                        <td>{{ pr.is_active }}</td>
                        <td><img src="{{ pr.provider_img.url }}" alt="Provider Image" class="img-thumbnail" style="width: 100px; height: auto;"></td>
                        <td><img src="{{ pr.vehicle_img.url }}" alt="Vehicle Image" class="img-thumbnail" style="width: 100px; height: auto;"></td>
                        <td>
                            <a href="{% url 'adminapp:delprovider' id=pr.id %}" class="btn btn-danger">Delete</a>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="12" class="text-center text-warning">No providers found.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock body %}

adminapp/templates/vehicle.html
<!-- templates/admin/vehicle/change_list.html -->
{% extends "adminparent.html" %}

{% block body %}
    <h1 class="text-center" style="color:olive;"><u>Vehicle Management</u></h1>
    <div class="container mt-5">
        
        <table class="table table-bordered  mt-4">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Price Per Day</th>
                    <th>Security Deposit</th>
                    <th>Image</th>
                    <th>Action</th>
                    
                </tr>
            </thead>
            <tbody>
                {% for vehicle in vehicle %}
                <tr>
                    <td>{{ vehicle.id }}</td>
                    <td>{{ vehicle.name }}</td>
                    <td>{{ vehicle.price_per_day }}</td>
                    <td>{{ vehicle.security_deposit }}</td>
                    <td><img src="{{ vehicle.image.url }}" alt="Vehicle Image" class="img-thumbnail" style="width: 100px; height: auto;"></td>
                    <td><a href="{% url 'adminapp:delvehicle' id=vehicle.id %}" class="btn btn-danger">Delete</a></td>
                    
                </tr>
                {% empty %}
                <tr>
                    <td colspan="7" class="text-center">No inquiries found.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}